# Generated by Django 4.2.3 on 2023-09-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightliftsession',
            name='warmup_set',
            field=models.BooleanField(default=False),
        ),
    ]
