# Generated by Django 4.2.3 on 2023-07-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not Specified')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
