# Generated by Django 4.2.3 on 2023-08-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
