# Generated by Django 4.2.3 on 2023-07-28 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_customexerciselist_exercises"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessions",
            name="custom_exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.customexerciselist",
            ),
        ),
        migrations.AlterField(
            model_name="sessions",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.exerciselist",
            ),
        ),
    ]
