# Generated by Django 4.2.3 on 2023-07-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_sessions_custom_exercise_alter_sessions_exercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="goals",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
