# Generated by Django 4.2.3 on 2023-08-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouthistory',
            name='user_specific_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
