# Generated by Django 4.2.3 on 2023-08-17 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_workouthistory_user_specific_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouthistory',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
