# Generated by Django 4.2.3 on 2023-08-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_workouthistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouthistory',
            name='user_specific_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
