# Generated by Django 4.2.3 on 2023-08-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_workouthistory_user_specific_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouthistory',
            old_name='user_specific_id',
            new_name='session_number',
        ),
    ]
