# Generated by Django 4.2.3 on 2023-08-17 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_user_specific_id_workouthistory_session_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='kgorlb',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='kmormiles',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='pace',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='session_duration',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='time',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='weight',
        ),
        migrations.AddField(
            model_name='sessions',
            name='exercise_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workouthistory',
            name='session_duration',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='WeightLiftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(null=True, unique=True)),
                ('weight', models.FloatField(null=True)),
                ('kgorlb', models.CharField(choices=[('kg', 'kilograms'), ('lb', 'pounds')], max_length=2, null=True)),
                ('reps', models.IntegerField(null=True)),
                ('inbetween_rest_time', models.TimeField(null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sessions')),
            ],
        ),
        migrations.CreateModel(
            name='RunningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pace', models.TimeField(null=True)),
                ('distance', models.FloatField(null=True)),
                ('kmormiles', models.CharField(choices=[('km', 'kilometers'), ('mi.', 'miles')], max_length=3, null=True)),
                ('time', models.TimeField(null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sessions')),
            ],
        ),
    ]
