# Generated by Django 4.2.3 on 2023-08-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_sessions_distance_remove_sessions_kgorlb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouthistory',
            name='session_notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
