# Generated by Django 4.2.3 on 2023-08-18 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_workouthistory_session_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customexerciselist',
            name='exercises',
        ),
        migrations.AddField(
            model_name='customexerciselist',
            name='custom_exercise_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customexerciselist',
            name='custom_exercise_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customexerciselist',
            name='linked_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.exerciselist'),
        ),
        migrations.AlterField(
            model_name='customexerciselist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
